enum ActionType {
    SESSION = 'SESSION',
    SET_AUTH_TOKEN = 'SET_AUTH_TOKEN',
    REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN',
    UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN',
    UPDATE_ROLES_USER = 'UPDATE_ROLES_USER',
    SET_FILE_CONVERT = 'SET_FILE_CONVERT',
    REMOVE_FILE_CONVERT = 'REMOVE_FILE_CONVERT'
}

export {ActionType}